# ~/.config/starship.toml

[python]
disabled = false
symbol = "python "
format = 'using [python ${pyenv_prefix}${version}]($style)[( \($virtualenv\))](72) '
style = "bold 72"
python_binary = "python3"

[directory]
style = "bold 223"

[time]
disabled = true
style = "243"
utc_time_offset = "-6"
use_12hr = true

[conda]
# symbol = "Ï¾ "
symbol = ""
format = "in [$environment]($style) "
style = "bold 79"

[git_commit]
disabled = false
commit_hash_length = 8
only_detached = false

[git_status]
style = "bold 210"
conflicted = "C"
untracked = "U"
stashed = "S"
modifed = "M"
renamed = "R"
